name: covr-csv-interview

services:
  db:
    platform: linux/x86_64
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:?err}
    volumes:
      - db:/var/lib/mysql
    ports:
      - "9999:3306"

volumes:
  db: {}

